GET http://localhost:3001/api/notes/

###
POST http://localhost:3001/api/notes/ 
content-type: application/json

{
    "content": "Ensure everything still works (this should appear when running npm run dev for the frontend)",
    "important": true
}